//
// VisionrangerAPIConfiguration+Version.swift
//
// This file was generated by update_version.sh
// Do not edit this file directly.
// Instead, edit the `VERSION` file and run `ci_scripts/update_version.sh`
//
import Foundation

public extension VisionrangerAPIConfiguration {
    /// The current version of this library.
    static let VSNSDKVersion = "0.7.0"
    
    /*
     NOTE: `VSNSDKVersion` must be a hard-coded static string instead of
     dynamically generated from the bundle's `CFBundleShortVersionString` to
     ensure the correct value is returned when the SDK is statically linked.
    */
}
