name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Package
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -scheme Visionranger -sdk iphoneos
    - name: Run tests
      run: xcodebuild test -scheme Visionranger -destination 'name=iPhone 11'
