name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Package
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios13.0-simulator"
    - name: Run tests
      run: swift test -v
