name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Package
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: xcodebuild clean build -scheme Visionranger -sdk iphoneos CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    - name: Run tests
      run: xcodebuild test -scheme Visionranger -destination 'name=iPhone 11' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    - name: Validate CocoaPod
      run: pod lib lint
